# logging:
#   level:
#     org.springframework: DEBUG
#     root: INFO

spring:
  profiles:
    active: shopping-service

---
spring:
  config:
    activate:
      on-profile: shopping-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 4000

---
spring:
  config:
    activate:
      on-profile: user-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 4001

